CREATE TABLE sber_user.counterparties
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    kpp character varying(9),
    account_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    bank_bik character varying(9) NOT NULL,
    inn character varying(12) NOT NULL,
    CONSTRAINT counterparties_pkey PRIMARY KEY (id),
    CONSTRAINT accountnumber_unique UNIQUE (account_number),
    CONSTRAINT name_unique UNIQUE (name),
    CONSTRAINT inn_unique UNIQUE (inn)
)